apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-depl
  labels:
    app: storage-conf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-conf
  template:
    metadata:
      labels:
        app: storage-conf
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index-file-1
          mountPath: /usr/share/nginx/html/
        - name: nginx-index-file-2
          mountPath: /etc/config/secret
      volumes:
      - name: nginx-index-file-1
        configMap:
          name: index-html-cm
      - name: nginx-index-file-2
        secret:
          secretName: my-tls-secret-1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-cm
  namespace: default
data:
  index.html: |
    <html>
    <h1>WELCOME HOME</h1>
    </br>
    <h1>We are glad to see you</h1>
    </html
---
apiVersion: v1
kind: Secret
metadata:
  name: my-tls-secret-1
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVakNDQWpvQ0NRQ1IvaWQzSktyaDdUQU5CZ2txaGtpRzl3MEJBUXNGQURCck1Rc3dDUVlEVlFRR0V3SlMKVlRFUE1BMEdBMVVFQ0F3R1RXOXpZMjkzTVE4d0RRWURWUVFIREFaTmIzTmpiM2N4RVRBUEJnTlZCQW9NQ0c1bApkRzlzYjJkNU1ROHdEUVlEVlFRTERBWmtaWFp2Y0hNeEZqQVVCZ05WQkFNTURUVXhMakkxTUM0Mk5pNHlNemd3CkhoY05Nak13TnpFM01UY3lNakF4V2hjTk1qUXdOekUyTVRjeU1qQXhXakJyTVFzd0NRWURWUVFHRXdKU1ZURVAKTUEwR0ExVUVDQXdHVFc5elkyOTNNUTh3RFFZRFZRUUhEQVpOYjNOamIzY3hFVEFQQmdOVkJBb01DRzVsZEc5cwpiMmQ1TVE4d0RRWURWUVFMREFaa1pYWnZjSE14RmpBVUJnTlZCQU1NRFRVeExqSTFNQzQyTmk0eU16Z3dnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRHRXalF0WlN6YmNNWXR3WlNtM1VhWFBwYXIKYUtCYzI3VEI3ZU5MZGhwL1hTTk8xQm1wbmRuVVRBbWxIbXUzeE1vblluZFk4NWl1RVVIN20wRk5HeUFPYlYyRgovems2cWhSaVBabkJGdUlSMnBOeUdsWmsvSWpKb3JXekNKTjZISXowN3ozbGkzQm1SQzRUdk5JOTJHRURjdEtBCkhOSTBHRENZUllocHRxSm50WHJCUEhTRTdteEIrZ2NPUWVrajc2TjlpOWVNVlluVkM1WThYZ0RjbWRWNWRvelYKczR0R0V4ZTFvbnVkQzI2Z2VaTlhFSTVFY2NKaytMdkZCNnhEZUpIZ0pCQlRjT2JnejlXaVVhblRoekYvZTI2LworRCttY3FPWnZlaEhuRUw0YkpGRlY5T2hFYklJVlFhYUhaZ3I2enVtVWpxYnlrc0Y5WVZEajNpT2IvK3pBZ01CCkFBRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTHlCQjc4cUU2V01tRzF5S0U5bWQ5OTZlQ0NldHpxSFJISW0KWjhrZE83bWJ4U1lvNmJaZXFZZnNHRnJPdTJiRnd4SFZjd3NQZGZRUWR5YUV1UnJKYWdtTEJLbGQ2ZTdpWFJYawp6TnV0SVB2YWRrN2xyT0xVT1pkM0s0WWRVdHpZTmltRG5tSGVYY3ZaTytlamV0K3dXYUVBUC9aYTUrdWVCNlNQCm81Z2dreEpFenBCbVcxZG56ZUxZc210MjlRdG5PbnJja3Z2dkxCNWVlRThobkI1WVptc3FTMVhJekdaOWh6bCsKdGRKZ0FwUDFoRXhYeUFjamZnZXRSdlNPblRxdXJ4QmR4eGFMVGtGY3kzcVFlaURGaHBGN2dwN29MU3NoRWlrSgpPSElIRHovZk1rRUMwYzZ1V2pZUGRNSkJyQnFWY2NOakVGRlk1Y25zd2NGL0R3K21tUWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRHRXalF0WlN6YmNNWXQKd1pTbTNVYVhQcGFyYUtCYzI3VEI3ZU5MZGhwL1hTTk8xQm1wbmRuVVRBbWxIbXUzeE1vblluZFk4NWl1RVVINwptMEZOR3lBT2JWMkYvems2cWhSaVBabkJGdUlSMnBOeUdsWmsvSWpKb3JXekNKTjZISXowN3ozbGkzQm1SQzRUCnZOSTkyR0VEY3RLQUhOSTBHRENZUllocHRxSm50WHJCUEhTRTdteEIrZ2NPUWVrajc2TjlpOWVNVlluVkM1WTgKWGdEY21kVjVkb3pWczR0R0V4ZTFvbnVkQzI2Z2VaTlhFSTVFY2NKaytMdkZCNnhEZUpIZ0pCQlRjT2JnejlXaQpVYW5UaHpGL2UyNi8rRCttY3FPWnZlaEhuRUw0YkpGRlY5T2hFYklJVlFhYUhaZ3I2enVtVWpxYnlrc0Y5WVZECmozaU9iLyt6QWdNQkFBRUNnZ0VCQUxnYlZ3dTdSZzgxSzlRRUt4MC8yR2lxMk00K2l0MWNZcHBtdnY4aXJpMEsKL3I4L2tHUmNGOEl2OU85S2FIMlVQTVpOLzR0VThLSmNxcFRTK2RVb2JEWWtxUDJ1V2lMaUdJdVhnck1lMzk2LwpiODE3Rm5hZzJDMm5jMDliSUtJQWtXblFSVy9QT0RGclExNTJBWktOUzdzVURxbm5NVG5OWmF4SGl5ZU16ZTZvCmZQV25xdzZsb2xFSS9nTjREb01QQ3FqdGM3Y1ROdHM3NjNsWnZIUFVtVTk0V1FVN2JZdTZHK1dKT0pPeENVZUMKdURHLzEyc2NGS015K0NDNnVJRHBiVnFxMjZwZWYrYjV3UXVmR2o4OWJUcnJBOXNTYlFacGlqN1lOdktaWlY1SgpWS1ZsRVlCdGVRT2c0OXVXLzhkZk41WVBBY0Z3dG9ySnRHMVpBZWFQcjhrQ2dZRUEvTnV4SGw5dkNvS0QxZG9lCnRleEdSaWRmM2JNeG1COUdWU01CV1dDaGN1M0VVQks1WW5JT05UZGRLUFFJY1I4T3kwZlA0SEV0OW1kOHduZmEKN1RNT2xWOE16dkU4WHNZck5Dcm4rYnd0T2J5SWFLS21OUlpDd1BOdWUyaUpXU1FUTmxyL3I5OWJwdWFjQVBjego5aWUyTDg5dy9uYmtFc0FPNkUwbElRTkJvdVVDZ1lFQThFMHdwWHhKc0hJUmc2VGhnY0J3V3NZRGRzVm8vSm0yCkxGbU1aOWU5UE5KSCtPdUxUTi9ZV1dDbUp4SGtLN0owNjVTWkc4dGhrZ0tzV05nVitRdFdrbFQzR0M4TGJxdWUKU2xrNHpNeVZ4dDhMR2dhcTVqUndyeHJ6RUJpT2xJWGUvNHBXRnpDS2xOa1YzSWFodVRDVlpmbSswMWhFcGVnNAp4ZFFnK1FIRGRyY0NnWUFkTmZnQkxUOHp0SjRzVDFWcTZNKzVmUVQ3Sko5ZkZvWFdnZ08rNG9Ya05BbVF3b2orCkVYVUl1c3VkVm91L0hicGt5M2Y5VXJYZm1GYjJWRWhMVExHcm1kNXQ3YnB1ckhBRFI4MmlzUlY4YlFaSktEa1IKT3ZBZFFFSU1LYWhzVHRtVlZ1L2d6bW5WSHlENGo1WkdJcEpPZGFWMUVDRUs5WHNEWlI0YjhUZGM3UUtCZ0dENAoxV3ZDcHo0VUdpdEV5MWdBSDVjU0YyM0RwbVZoWmxtcFhYYStZZmg4WjF6MU9NYXlBbTIzQ2ZYMFMxNnk2bW56CkVvSmI1YWoxZVRWMUpoRFZXWDg5MkdVaS92c1BPSmFLUU5pc3FyaVJZN3FCL0U5ZjFDVmx1N2JBSWpHZmdHa2gKR3pMS2ZQSXFWSjhrbVhqUk9Vam9xdkJBeTVza0JsMFhDS05UNmR3ckFvR0JBTE9WQXZ5OEpBVkhEZE5BWXVFbApOZ0NXTWdSamo4NzFjK1pBeThRVnlITjhFbWpIYUxwTUY5aTRvblV4bldPbVZsZHBRN0hKbll5ZmdIMThKNnJkClY4c3Y4Rm9IczFmcFpvNmozczNIbGw1YXNhalZFUFNjb0lrNDlrdk1mMDFVL0NYS1pUR0Yyd2x2ZFpsbkw0cHQKS3I1cmUxWUxySEM3c0JZSnRDWXZUMXJ5Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: v1
kind: Service
metadata:
  name: storage-conf
  namespace: default
spec:
  selector:
    app: storage-conf
  type: ClusterIP
  ports:
    - port: 3333
      targetPort: 80
      protocol: TCP
      name: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conf-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  tls:
  - hosts:
      - micro.ru-central1.internal
    secretName: my-tls-secret-1
  rules:
  - host: micro.ru-central1.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: storage-conf
            port:
              name: nginx