---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-cm
  namespace: default
data:
  index.html: |
    <html>
    <h1>WELCOME HOME</h1>
    </br>
    <h1>We are glad to see you</h1>
    </html