---
apiVersion: v1
kind: Service
metadata:
  name: nginx-multi-network-task2-s
  namespace: default
spec:
  selector:
    app: nginx-multi-network
  ports:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30020
    name: port-1
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30021
    name: port-2
# kubectl expose deployment/nginx-multi-network-task1 --type=NodePort - название deployment
# kubectl describe svc nginx-multi-network-task1
# You can access your application by entering `http://<public-node-ip>:<node-port>` in your browser.