apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: from-frontend-to-backend
  namespace: app
spec:
  podSelector:
    matchLabels:
        app: backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
        ports:
          - port: 80
            protocol: TCP
#запрещает входящий трафик кроме фронтенда
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: from-backend-to-cache
  namespace: app
spec:
  podSelector:
    matchLabels:
        app: cache
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
        ports:
          - port: 80
            protocol: TCP